// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKl0zqT3s6gFf02CTph6M-jiiqnCQ5ngk',
    appId: '1:1012244723831:android:a34f68f502a08dbfe46e72',
    messagingSenderId: '1012244723831',
    projectId: 'tapontask',
    storageBucket: 'tapontask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE3cMY_RuUneHA_HOXDtJ63ja_-SH4AB4',
    appId: '1:1012244723831:ios:6d6382bf89734348e46e72',
    messagingSenderId: '1012244723831',
    projectId: 'tapontask',
    storageBucket: 'tapontask.firebasestorage.app',
    androidClientId: '1012244723831-9doungfk2jv7f5ltb0vgegghevh96ge1.apps.googleusercontent.com',
    iosClientId: '1012244723831-6013kmbaic235gsngu9simou68j5161a.apps.googleusercontent.com',
    iosBundleId: 'com.app.tapontask',
  );
}
